# 판다스 10분 완성

In [1]:
# 패키지 import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 객체 생성
판다스는 값을 가지고 있는 리스트로 시리스를 만들고 정수로 만들어진 인덱스를 기본값으로 불러옴

In [3]:
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# 넘파이 배열로 df 만들기
dates = pd.date_range('20210101', periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [6]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2021-01-01  0.695457 -0.281311 -0.900917  0.907423
2021-01-02  1.542615 -0.869835  0.845573  0.732221
2021-01-03  0.701550 -0.683680 -0.673744 -1.889198
2021-01-04 -0.757824 -0.780853  0.788621 -0.964549
2021-01-05 -1.203066  1.150476 -0.596711 -0.394439
2021-01-06 -1.544740  0.127456 -1.138046 -2.708949

In [7]:
# 딕셔너리로 df 만들기

df2 = pd.DataFrame({'A' : 1,
                    'B' : pd.Timestamp('20210101'),
                    'C' : pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D' : np.array([3] * 4, dtype='int32'),
                    'E' : pd.Categorical(['test', 'train', 'test', 'train']),
                    'F' : 'foo'})
df2

   A          B    C  D      E    F
0  1 2021-01-01  1.0  3   test  foo
1  1 2021-01-01  1.0  3  train  foo
2  1 2021-01-01  1.0  3   test  foo
3  1 2021-01-01  1.0  3  train  foo

In [8]:
# df 타입보기
df2.dtypes

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

## 데이터 확인하기

In [9]:
df.tail()  # 뒤에서 5줄
df.head(3)  # 앞에서 3줄

                   A         B         C         D
2021-01-01  0.695457 -0.281311 -0.900917  0.907423
2021-01-02  1.542615 -0.869835  0.845573  0.732221
2021-01-03  0.701550 -0.683680 -0.673744 -1.889198

In [10]:
df.index   # 인덱스 정보

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df.columns # 열 정보

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.values   # 데이터 정보

array([[ 0.69545661, -0.28131124, -0.90091673,  0.9074227 ],
       [ 1.54261509, -0.86983475,  0.84557264,  0.73222102],
       [ 0.70155033, -0.68368038, -0.67374371, -1.88919797],
       [-0.75782398, -0.78085279,  0.78862091, -0.96454884],
       [-1.20306648,  1.15047624, -0.59671109, -0.39443861],
       [-1.54474029,  0.1274565 , -1.13804606, -2.70894922]])

In [13]:
df.describe()   # 대략적인 통계정보

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.094335 -0.222958 -0.279204 -0.719582
std    1.241772  0.768697  0.870170  1.431516
min   -1.544740 -0.869835 -1.138046 -2.708949
25%   -1.091756 -0.756560 -0.844123 -1.658036
50%   -0.031184 -0.482496 -0.635227 -0.679494
75%    0.700027  0.025265  0.442288  0.450556
max    1.542615  1.150476  0.845573  0.907423

In [14]:
df.T   # 데이터 전치

   2021-01-01  2021-01-02  2021-01-03  2021-01-04  2021-01-05  2021-01-06
A    0.695457    1.542615    0.701550   -0.757824   -1.203066   -1.544740
B   -0.281311   -0.869835   -0.683680   -0.780853    1.150476    0.127456
C   -0.900917    0.845573   -0.673744    0.788621   -0.596711   -1.138046
D    0.907423    0.732221   -1.889198   -0.964549   -0.394439   -2.708949

In [15]:
df.sort_index(axis=1, ascending=False)   # 축 별로 정렬

                   D         C         B         A
2021-01-01  0.907423 -0.900917 -0.281311  0.695457
2021-01-02  0.732221  0.845573 -0.869835  1.542615
2021-01-03 -1.889198 -0.673744 -0.683680  0.701550
2021-01-04 -0.964549  0.788621 -0.780853 -0.757824
2021-01-05 -0.394439 -0.596711  1.150476 -1.203066
2021-01-06 -2.708949 -1.138046  0.127456 -1.544740

In [16]:
df.sort_values(by='B')   # 값 별로 정렬

                   A         B         C         D
2021-01-02  1.542615 -0.869835  0.845573  0.732221
2021-01-04 -0.757824 -0.780853  0.788621 -0.964549
2021-01-03  0.701550 -0.683680 -0.673744 -1.889198
2021-01-01  0.695457 -0.281311 -0.900917  0.907423
2021-01-06 -1.544740  0.127456 -1.138046 -2.708949
2021-01-05 -1.203066  1.150476 -0.596711 -0.394439

## 인덱싱 하기

In [17]:
df['A']  # 단일 열 
df[0:3]  # 행 분활

                   A         B         C         D
2021-01-01  0.695457 -0.281311 -0.900917  0.907423
2021-01-02  1.542615 -0.869835  0.845573  0.732221
2021-01-03  0.701550 -0.683680 -0.673744 -1.889198

In [19]:
df.loc[:, ['A', 'B']]   # 라벨로 선택하기

                   A         B
2021-01-01  0.695457 -0.281311
2021-01-02  1.542615 -0.869835
2021-01-03  0.701550 -0.683680
2021-01-04 -0.757824 -0.780853
2021-01-05 -1.203066  1.150476
2021-01-06 -1.544740  0.127456