<a href="https://colab.research.google.com/github/BOSOEK/Machine_Learning_with_Book/blob/main/Rookie_League/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd drive/Othercomputers/내 노트북/googleDrive/BigContest/Rookie_League/01_제공데이터

/content/drive/Othercomputers/내 노트북/googleDrive/BigContest/Rookie_League/01_제공데이터

In [4]:
cd 팀타자/

/content/drive/Othercomputers/내 노트북/googleDrive/BigContest/Rookie_League/01_제공데이터/팀타자

In [5]:
ls

'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2016.csv'
'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2017.csv'
'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2018.csv'
'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2019.csv'
'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2020.csv'
'2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2021.csv'

## 데이터 불러오기

In [15]:
import pandas as pd

df_2016 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2016.csv')
df_2017 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2017.csv')
df_2018 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2018.csv')
df_2019 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2019.csv')
df_2020 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2020.csv')
df_2021 = pd.read_csv('2021 빅콘테스트_데이터분석분야_루키리그_팀타자_2021.csv')
df_2021.head()

            G_ID   GDAY_DS T_ID VS_T_ID  ...  LOB  P_HRA_RT  P_AB_CN  P_HIT_CN
0  20210403SSWO0  20210403   WO      SS  ...    6  0.222222        9         2
1  20210403SSWO0  20210403   SS      WO  ...    4  0.250000        4         1
2  20210404HHKT0  20210404   HH      KT  ...    9  0.200000       10         2
3  20210404HHKT0  20210404   KT      HH  ...    6  0.250000        4         1
4  20210404HTOB0  20210404   HT      OB  ...    9  0.166667        6         1

[5 rows x 28 columns]

In [26]:
df = df_2017['T_ID'].value_counts()
df

NC    144
SS    144
KT    144
HT    144
OB    144
LT    144
LG    144
WO    144
HH    144
SK    144
Name: T_ID, dtype: int64

## 팀 별로 데이터 나누기

In [28]:
WO = df_2016['T_ID'] == 'WO'
dfsec = df_2016[WO]
'''
WO = df_2017['T_ID'] == 'WO'
dfsec=dfsec.append(WO, ignore_index=True)

WO = df_2018['T_ID'] == 'WO'
dfsec=dfsec.append(WO, ignore_index=True)

WO = df_2019['T_ID'] == 'WO'
dfsec=dfsec.append(WO, ignore_index=True)

WO = df_2020['T_ID'] == 'WO'
dfsec=dfsec.append(WO, ignore_index=True)

WO = df_2021['T_ID'] == 'WO'
dfsec=dfsec.append(WO, ignore_index=True)
'''

dfsec

              G_ID     GDAY_DS T_ID VS_T_ID  ...  1436 1437  1438  1439
0    20160401LTWO0  20160401.0   WO      LT  ...   NaN  NaN   NaN   NaN
1    20160402LTWO0  20160402.0   WO      LT  ...   NaN  NaN   NaN   NaN
2    20160403LTWO0  20160403.0   WO      LT  ...   NaN  NaN   NaN   NaN
3    20160405WOHH0  20160405.0   WO      HH  ...   NaN  NaN   NaN   NaN
4    20160406WOHH0  20160406.0   WO      HH  ...   NaN  NaN   NaN   NaN
..             ...         ...  ...     ...  ...   ...  ...   ...   ...
140  20161004WONC0  20161004.0   WO      NC  ...   NaN  NaN   NaN   NaN
141  20161005WONC0  20161005.0   WO      NC  ...   NaN  NaN   NaN   NaN
142  20161007WOLT0  20161007.0   WO      LT  ...   NaN  NaN   NaN   NaN
143  20161009WOLT0  20161009.0   WO      LT  ...   NaN  NaN   NaN   NaN
144            NaN         NaN  NaN     NaN  ...   0.0  0.0   1.0   0.0

[145 rows x 1468 columns]